sudo: false
language: node_js
cache:
  directories:
    - node_modules
node_js:
  - stable
after_success:
  - 'travis-after-all && npm run semantic-release'
env:
  global:
    - secure: v+aA0usmcsTo3Ovyj4YOJ8+Az+BsF/cpxeec4aq4pmHEgYC6gDkLY6Q2wcI33ThCn26+IgGXG5ZxGWWP5QEYA3DDs1MzJLvUh4MMg8onPniz0s2GNQ3f5W5G4gNpVbOLt0kf27PtgjXN7I62EBdHTno6T+FMH2B/CETdejmewMkynQ4f1cC/J64rbaRI86JOrwuj2gdyhlZiJC9SZ9IfJ0hcY2mFFOmZF2U2p0Gf9z8QLYQkPe+AWjtrV6cHmXIfiknpZ0O9f5GDi0mKDpxQKo7naTVrw8d8b/eTYIU3HZeC0aQpXyzrXoI+979sWH0UzQOb5k/dzV4COFptwvHUXOW20vsZfif8h0LcQVfsgRJ60gsXM4bWH5ydW/aHa47AyA9m9jwBzPehpNTPaRYPMfSnZBIA3x28sp/0h2E7ci0riwo0aZbgbuF1UgAs/IklXfrJpMgL3W8FjB7S/PNrN1sRFnTu6Mhh/8bFhJX+BA1+Jp5nPzY6xeM3VMXt+4Q8SPlVtRDxFeF001KxBBi3vZ8DRpqLfH3sEEO0z3aZF0xh4weNuuMSuZZNhh2YxRFPZDBnNvi2nH+/JsByLCTE71rY+bQWIeNp3RVhsOfVn+ToICRjcGeJDvImF2KkXefbdGeRw+I2aCsHpG/hKGMGB631PI3HlRKq8aF9mJRj9YI=
    - secure: FF5P97OehpegiUYWDdkZMFwZS9z0DKXNaTmdtuVfZjTZqjW7WdKXB6dip235EXaNuPtO/vAwRhryXLd0yEdm67DKWZ+y6Lxo7y1ZkEzSrxUKDfyd1vvTgszQETdf0ZNf9DifZbyBcz6zTxqRtP3Vus3flKCwpadzHPOjLjx2aHqMQ2NtB8+OvJVkTKuGL2iIr390CaVd8zXUfnTpVHyetehpujYjuUyY/8DbmG29ttA9rQ3itpb/AxK+8za2ypHClO+9TeDkNKT1PhfLavmcdN7/zh6vQKxjLD3MAC1EGPPLWrP9r0GVfq9h4TfbdoibtgqXdauQ0kLVL6pTm2I+LMeYzONWmrmUSsKmK43pG0JzfVjYSzVGVswptZOcNIfWBcyBtWUxxKZORPKm7XncAjCk9Ut10MIEIWD7yPdDrV9vLfZqioiBan/CdZ/CntduDcxiTJfP5SAAnVT8kA/qvnG777/06QkTTWtwgrk8KhNsiGIp59gvKCMQx8BRal6/oWUZWkBZAnQXKJEMGYMdNM2tNSzD8JDlYRDJ1ahCouURHgYeRS04fMd5cAZnmtF7Eg/NiMKgpbH7TFuQJNlPhABaNVZ9V362LEZ/r3aXfgtMFZ8BksPOgCLTLzqYdiH2r9hsrPebckoC54PDYz6DB7J8Mweph/XXUWBXwHG7pwo=
